---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-src
  - name: environment
  - name: director-config

outputs:
  - name: bats-config

run:
  path: bosh-src/ci/pipelines/aws-bats/tasks/prepare-manual-bats.sh

params:
  AWS_ACCESS_KEY:     ""
  AWS_SECRET_KEY:     ""
  AWS_REGION_NAME:    ""
  AWS_STACK_NAME:     ""
  BAT_VCAP_PASSWORD:  ""
  PUBLIC_KEY_NAME:    ""
  STEMCELL_NAME:      ""
  BOSH_DIRECTOR_USERNAME: ""
  BOSH_DIRECTOR_PASSWORD: ""
