---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-src
  - name: bosh-release
  - name: cpi-release
  - name: stemcell
  - name: environment

outputs:
  - name: director-config

run:
  path: bosh-src/ci/pipelines/aws-bats/tasks/prepare-director.sh

params:
  AWS_ACCESS_KEY:         ""
  AWS_SECRET_KEY:         ""
  AWS_REGION_NAME:        ""
  AWS_STACK_NAME:         ""
  BOSH_DIRECTOR_USERNAME: ""
  BOSH_DIRECTOR_PASSWORD: ""
  PUBLIC_KEY_NAME:        ""
  PRIVATE_KEY_DATA:       ""
  USE_REDIS:              ""
