---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder

inputs:
- name: bosh-src

outputs:
- name: os-image

run:
  path: bosh-src/ci/pipelines/os-images-new/tasks/build.sh

params:
  OPERATING_SYSTEM_NAME:      replace-me
  OPERATING_SYSTEM_VERSION:   replace-me
