VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # trusty (latest), virtualbox only
  config.vm.box = 'ubuntu/trusty64'

  config.vm.provider(:virtualbox) do |v|
    v.name = 'bosh-docker-builder'
    v.customize ['modifyvm', :id, '--cpus', '4']
    v.customize ['modifyvm', :id, '--memory', '4096']
  end

  # mount bosh dir for testing
  config.vm.synced_folder('../../', '/opt/bosh', owner: 'root', group: 'root')

  if Vagrant.has_plugin?("vagrant-proxyconf")
    http_proxy = ENV["HTTP_PROXY"] || ENV["http_proxy"]
    if http_proxy
      config.proxy.http        = http_proxy
      config.apt_proxy.http    = http_proxy
    end
    https_proxy = ENV["HTTPS_PROXY"] || ENV["https_proxy"]
    if https_proxy
      config.proxy.https        = https_proxy
      config.apt_proxy.https    = https_proxy
    end
    no_proxy = ENV["NO_PROXY"] || ENV["no_proxy"]
    if no_proxy
      config.proxy.no_proxy     = no_proxy
    end
  end

  config.vm.provision('docker')
end
