---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-src
  - name: bosh-release
  - name: cpi-release
  - name: stemcell
  - name: bosh-cli

outputs:
  - name: director-state

run:
  path: bosh-src/ci/pipelines/stemcells/tasks/deploy-director.sh

params:
  BOSH_DIRECTOR_USERNAME:               ""
  BOSH_DIRECTOR_PASSWORD:               ""
  BOSH_VSPHERE_VCENTER:                 ""
  BOSH_VSPHERE_VCENTER_USER:            ""
  BOSH_VSPHERE_VCENTER_PASSWORD:        ""
  BOSH_VSPHERE_VCENTER_DC:              ""
  BOSH_VSPHERE_VCENTER_CLUSTER:         ""
  BOSH_VSPHERE_VCENTER_VM_FOLDER:       ""
  BOSH_VSPHERE_VCENTER_TEMPLATE_FOLDER: ""
  BOSH_VSPHERE_VCENTER_DATASTORE:       ""
  BOSH_VSPHERE_VCENTER_DISK_PATH:       ""
  BOSH_VSPHERE_VCENTER_VLAN:            ""
  DIRECTOR_IP:                          ""
  BOSH_VSPHERE_VCENTER_CIDR:            ""
  BOSH_VSPHERE_VCENTER_GATEWAY:         ""
  BOSH_VSPHERE_DNS:                     ""
