---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-src
  - name: director-state
  - name: bosh-cli
  - name: cpi-release

run:
  path: bosh-src/ci/pipelines/stemcells/tasks/teardown.sh
