---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/compiled-release

inputs:
  - name: bosh-src
  - name: director-state
  - name: bosh-cli

run:
  path: bosh-src/ci/pipelines/compiled-releases/tasks/delete-bosh-env.sh

params:
  SL_VM_PREFIX:         replace-me
  SL_API_KEY:           replace-me
  SL_DATACENTER:        replace-me
  SL_VLAN_PUBLIC:       replace-me
  SL_VLAN_PRIVATE:      replace-me
  SL_USERNAME:          replace-me