---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/compiled-release

inputs:
  - name: bosh-src
  - name: stemcell
  - name: release
  - name: director-state

outputs:
  - name: compiled-release

run:
  path: bosh-src/ci/pipelines/compiled-releases/tasks/export-director-release.sh