---
groups: []
resource_types: []

resources:
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: {{branch}}

  - name: bosh-aws-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-aws-cpi-release

  #
  # releases to compile
  #
  - name: bosh-release-255
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bosh-release-257
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: uaa-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/uaa-release

  - name: uaa-release-3232
    type: bosh-io-release
    source:
      repository: cloudfoundry/uaa-release

  #
  # stemcells to compile on
  #
  - name: ubuntu-trusty-3232-stemcell
    type: s3
    source:
      bucket: bosh-jenkins-artifacts
      regexp: "bosh-stemcell/aws/light-bosh-stemcell-(?P<version>3232\\.[^-]+)-aws-xen-hvm-ubuntu-trusty-go_agent.tgz"

  - name: ubuntu-trusty-3233-stemcell
    type: s3
    source:
      bucket: bosh-jenkins-artifacts
      regexp: "bosh-stemcell/aws/light-bosh-stemcell-(?P<version>3233\\.[^-]+)-aws-xen-hvm-ubuntu-trusty-go_agent.tgz"

  - name: ubuntu-trusty-3262-stemcell
    type: s3
    source:
      bucket: bosh-jenkins-artifacts
      regexp: "bosh-stemcell/aws/light-bosh-stemcell-(?P<version>3262(\\.[^-]+)?)-aws-xen-hvm-ubuntu-trusty-go_agent.tgz"

  - name: ubuntu-trusty-3263-stemcell
    type: s3
    source:
      bucket: bosh-jenkins-artifacts
      regexp: "bosh-stemcell/aws/light-bosh-stemcell-(?P<version>3263(\\.[^-]+)?)-aws-xen-hvm-ubuntu-trusty-go_agent.tgz"

  #
  # compiled releases
  #

  # ubuntu-trusty-3232

  - name: bosh-on-ubuntu-trusty-3232
    type: s3
    source:
      bucket: "bosh-compiled-release-tarballs"
      access_key_id: {{aws_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      regexp: "release-bosh-[\\d\\.]+-on-ubuntu-trusty-stemcell-3232.*-(\\d+).tgz"

  - name: uaa-on-ubuntu-trusty-3232
    type: s3
    source:
      bucket: "bosh-compiled-release-tarballs"
      access_key_id: {{aws_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      regexp: "release-uaa-[\\d\\.]+-on-ubuntu-trusty-stemcell-3232.*-(\\d+).tgz"

  # ubuntu-trusty-3262

  - name: bosh-on-ubuntu-trusty-3262
    type: s3
    source:
      bucket: "bosh-compiled-release-tarballs"
      access_key_id: {{aws_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      regexp: "release-bosh-[\\d\\.]+-on-ubuntu-trusty-stemcell-3262.*-(\\d+).tgz"

  - name: uaa-on-ubuntu-trusty-3262
    type: s3
    source:
      bucket: "bosh-compiled-release-tarballs"
      access_key_id: {{aws_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      regexp: "release-uaa-[\\d\\.]+-on-ubuntu-trusty-stemcell-3262.*-(\\d+).tgz"

  # ubuntu-trusty-3263

  - name: bosh-on-ubuntu-trusty-3263
    type: s3
    source:
      bucket: "bosh-compiled-release-tarballs"
      access_key_id: {{aws_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      regexp: "release-bosh-[\\d\\.]+-on-ubuntu-trusty-stemcell-3263.*-(\\d+).tgz"

  - name: uaa-on-ubuntu-trusty-3263
    type: s3
    source:
      bucket: "bosh-compiled-release-tarballs"
      access_key_id: {{aws_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      regexp: "release-uaa-[\\d\\.]+-on-ubuntu-trusty-stemcell-3263.*-(\\d+).tgz"

  # ubuntu-trusty-3233

  - name: bosh-on-ubuntu-trusty-3233
    type: s3
    source:
      bucket: "bosh-compiled-release-tarballs"
      access_key_id: {{aws_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      regexp: "release-bosh-[\\d\\.]+-on-ubuntu-trusty-stemcell-3233.*-(\\d+).tgz"

  - name: uaa-on-ubuntu-trusty-3233
    type: s3
    source:
      bucket: "bosh-compiled-release-tarballs"
      access_key_id: {{aws_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      regexp: "release-uaa-[\\d\\.]+-on-ubuntu-trusty-stemcell-3233.*-(\\d+).tgz"


jobs:
  - name: compile-bosh-release-latest-ubuntu-trusty-3232
    plan:
      - aggregate:
          - get: bosh-src
          - get: bosh-release-255
            trigger: true
            version:
              version: "255.12"
          - get: bosh-aws-cpi-release
          - get: ubuntu-trusty-3232-stemcell
            trigger: true
      - task: deploy-director
        file: bosh-src/ci/pipelines/compiled-releases/tasks/deploy-director.yml
        input_mapping:
          stemcell: ubuntu-trusty-3232-stemcell
          bosh-release: bosh-release-255
        params:
          BOSH_INIT_ACCESS_KEY: {{bosh_init_access_key}}
          BOSH_INIT_SECRET_KEY: {{bosh_init_secret_key}}
          BOSH_SSH_TUNNEL_KEY: {{bosh_ssh_tunnel_key}}
          BOSH_TARGET_IP: 10.0.2.7
          BOSH_RESERVED_RANGES: [10.0.2.0-10.0.2.19, 10.0.2.30-10.0.2.255]
          BOSH_REDIS: true
      - do:
        - task: export-release
          file: bosh-src/ci/pipelines/compiled-releases/tasks/export-release.yml
          input_mapping:
            stemcell: ubuntu-trusty-3232-stemcell
            release: bosh-release-255
          params:
            BOSH_TARGET_IP: 10.0.2.7
        - put: bosh-on-ubuntu-trusty-3232
          params:
            file: "compiled-release/*.tgz"
        ensure:
          task: teardown-director
          file: bosh-src/ci/pipelines/compiled-releases/tasks/teardown-director.yml

  - name: compile-bosh-release-latest-ubuntu-trusty-3262
    plan:
      - aggregate:
          - get: bosh-src
          - get: bosh-release-257
            trigger: true
          - get: bosh-aws-cpi-release
          - get: ubuntu-trusty-3262-stemcell
            trigger: true
      - task: deploy-director
        file: bosh-src/ci/pipelines/compiled-releases/tasks/deploy-director.yml
        input_mapping:
          stemcell: ubuntu-trusty-3262-stemcell
          bosh-release: bosh-release-257
        params:
          BOSH_INIT_ACCESS_KEY: {{bosh_init_access_key}}
          BOSH_INIT_SECRET_KEY: {{bosh_init_secret_key}}
          BOSH_SSH_TUNNEL_KEY: {{bosh_ssh_tunnel_key}}
          BOSH_TARGET_IP: 10.0.2.8
          BOSH_RESERVED_RANGES: [10.0.2.0-10.0.2.29, 10.0.2.40-10.0.2.255]
      - do:
        - task: export-release
          file: bosh-src/ci/pipelines/compiled-releases/tasks/export-release.yml
          input_mapping:
            stemcell: ubuntu-trusty-3262-stemcell
            release: bosh-release-257
          params:
            BOSH_TARGET_IP: 10.0.2.8
        - put: bosh-on-ubuntu-trusty-3262
          params:
            file: "compiled-release/*.tgz"
        ensure:
          task: teardown-director
          file: bosh-src/ci/pipelines/compiled-releases/tasks/teardown-director.yml

  - name: compile-uaa-release-latest-ubuntu-trusty-3232
    plan:
      - aggregate:
          - get: bosh-src
          - get: uaa-release-3232
            trigger: true
          - get: bosh-release-255
            version:
              version: "255.12"
          - get: bosh-aws-cpi-release
          - get: ubuntu-trusty-3232-stemcell
            trigger: true
      - task: deploy-director
        file: bosh-src/ci/pipelines/compiled-releases/tasks/deploy-director.yml
        input_mapping:
          stemcell: ubuntu-trusty-3232-stemcell
          bosh-release: bosh-release-255
        params:
          BOSH_INIT_ACCESS_KEY: {{bosh_init_access_key}}
          BOSH_INIT_SECRET_KEY: {{bosh_init_secret_key}}
          BOSH_SSH_TUNNEL_KEY: {{bosh_ssh_tunnel_key}}
          BOSH_TARGET_IP: 10.0.2.9
          BOSH_RESERVED_RANGES: [10.0.2.0-10.0.2.39, 10.0.2.50-10.0.2.255]
          BOSH_REDIS: true
      - do:
        - task: export-release
          file: bosh-src/ci/pipelines/compiled-releases/tasks/export-release.yml
          input_mapping:
            stemcell: ubuntu-trusty-3232-stemcell
            release: uaa-release-3232
          params:
            BOSH_TARGET_IP: 10.0.2.9
        - put: uaa-on-ubuntu-trusty-3232
          params:
            file: "compiled-release/*.tgz"
        ensure:
          task: teardown-director
          file: bosh-src/ci/pipelines/compiled-releases/tasks/teardown-director.yml

  - name: compile-uaa-release-latest-ubuntu-trusty-3262
    plan:
      - aggregate:
          - get: bosh-src
          - get: uaa-release
            trigger: true
          - get: bosh-release-257
          - get: bosh-aws-cpi-release
          - get: ubuntu-trusty-3262-stemcell
            trigger: true
      - task: deploy-director
        file: bosh-src/ci/pipelines/compiled-releases/tasks/deploy-director.yml
        input_mapping:
          stemcell: ubuntu-trusty-3262-stemcell
          bosh-release: bosh-release-257
        params:
          BOSH_INIT_ACCESS_KEY: {{bosh_init_access_key}}
          BOSH_INIT_SECRET_KEY: {{bosh_init_secret_key}}
          BOSH_SSH_TUNNEL_KEY: {{bosh_ssh_tunnel_key}}
          BOSH_TARGET_IP: 10.0.2.10
          BOSH_RESERVED_RANGES: [10.0.2.0-10.0.2.49, 10.0.2.60-10.0.2.255]
      - do:
        - task: export-release
          file: bosh-src/ci/pipelines/compiled-releases/tasks/export-release.yml
          input_mapping:
            stemcell: ubuntu-trusty-3262-stemcell
            release: uaa-release
          params:
            BOSH_TARGET_IP: 10.0.2.10
        - put: uaa-on-ubuntu-trusty-3262
          params:
            file: "compiled-release/*.tgz"
        ensure:
          task: teardown-director
          file: bosh-src/ci/pipelines/compiled-releases/tasks/teardown-director.yml

  - name: compile-bosh-release-latest-ubuntu-trusty-3263
    plan:
      - aggregate:
          - get: bosh-src
          - get: bosh-release-257
            trigger: true
          - get: bosh-aws-cpi-release
          - get: ubuntu-trusty-3263-stemcell
            trigger: true
      - task: deploy-director
        file: bosh-src/ci/pipelines/compiled-releases/tasks/deploy-director.yml
        input_mapping:
          stemcell: ubuntu-trusty-3263-stemcell
          bosh-release: bosh-release-257
        params:
          BOSH_INIT_ACCESS_KEY: {{bosh_init_access_key}}
          BOSH_INIT_SECRET_KEY: {{bosh_init_secret_key}}
          BOSH_SSH_TUNNEL_KEY: {{bosh_ssh_tunnel_key}}
          BOSH_TARGET_IP: 10.0.2.11
          BOSH_RESERVED_RANGES: [10.0.2.0-10.0.2.59, 10.0.2.70-10.0.2.255]
      - do:
        - task: export-release
          file: bosh-src/ci/pipelines/compiled-releases/tasks/export-release.yml
          input_mapping:
            stemcell: ubuntu-trusty-3263-stemcell
            release: bosh-release-257
          params:
            BOSH_TARGET_IP: 10.0.2.11
        - put: bosh-on-ubuntu-trusty-3263
          params:
            file: "compiled-release/*.tgz"
        ensure:
          task: teardown-director
          file: bosh-src/ci/pipelines/compiled-releases/tasks/teardown-director.yml

  - name: compile-uaa-release-latest-ubuntu-trusty-3263
    plan:
      - aggregate:
          - get: bosh-src
          - get: uaa-release
            trigger: true
          - get: bosh-release-257
          - get: bosh-aws-cpi-release
          - get: ubuntu-trusty-3263-stemcell
            trigger: true
      - task: deploy-director
        file: bosh-src/ci/pipelines/compiled-releases/tasks/deploy-director.yml
        input_mapping:
          stemcell: ubuntu-trusty-3263-stemcell
          bosh-release: bosh-release-257
        params:
          BOSH_INIT_ACCESS_KEY: {{bosh_init_access_key}}
          BOSH_INIT_SECRET_KEY: {{bosh_init_secret_key}}
          BOSH_SSH_TUNNEL_KEY: {{bosh_ssh_tunnel_key}}
          BOSH_TARGET_IP: 10.0.2.12
          BOSH_RESERVED_RANGES: [10.0.2.0-10.0.2.69, 10.0.2.80-10.0.2.255]
      - do:
        - task: export-release
          file: bosh-src/ci/pipelines/compiled-releases/tasks/export-release.yml
          input_mapping:
            stemcell: ubuntu-trusty-3263-stemcell
            release: uaa-release
          params:
            BOSH_TARGET_IP: 10.0.2.12
        - put: uaa-on-ubuntu-trusty-3263
          params:
            file: "compiled-release/*.tgz"
        ensure:
          task: teardown-director
          file: bosh-src/ci/pipelines/compiled-releases/tasks/teardown-director.yml

  - name: compile-bosh-release-latest-ubuntu-trusty-3233
    plan:
      - aggregate:
          - get: bosh-src
          - get: bosh-release-255
            trigger: true
          - get: bosh-aws-cpi-release
          - get: ubuntu-trusty-3233-stemcell
            trigger: true
      - task: deploy-director
        file: bosh-src/ci/pipelines/compiled-releases/tasks/deploy-director.yml
        input_mapping:
          stemcell: ubuntu-trusty-3233-stemcell
          bosh-release: bosh-release-255
        params:
          BOSH_INIT_ACCESS_KEY: {{bosh_init_access_key}}
          BOSH_INIT_SECRET_KEY: {{bosh_init_secret_key}}
          BOSH_SSH_TUNNEL_KEY: {{bosh_ssh_tunnel_key}}
          BOSH_TARGET_IP: 10.0.2.13
          BOSH_RESERVED_RANGES: [10.0.2.0-10.0.2.79, 10.0.2.90-10.0.2.255]
          BOSH_REDIS: true
      - do:
        - task: export-release
          file: bosh-src/ci/pipelines/compiled-releases/tasks/export-release.yml
          input_mapping:
            stemcell: ubuntu-trusty-3233-stemcell
            release: bosh-release-255
          params:
            BOSH_TARGET_IP: 10.0.2.13
        - put: bosh-on-ubuntu-trusty-3233
          params:
            file: "compiled-release/*.tgz"
        ensure:
          task: teardown-director
          file: bosh-src/ci/pipelines/compiled-releases/tasks/teardown-director.yml

  - name: compile-uaa-release-latest-ubuntu-trusty-3233
    plan:
      - aggregate:
          - get: bosh-src
          - get: uaa-release-3232
            trigger: true
          - get: bosh-release-255
            version:
              version: "255.12"
          - get: bosh-aws-cpi-release
          - get: ubuntu-trusty-3233-stemcell
            trigger: true
      - task: deploy-director
        file: bosh-src/ci/pipelines/compiled-releases/tasks/deploy-director.yml
        input_mapping:
          stemcell: ubuntu-trusty-3233-stemcell
          bosh-release: bosh-release-255
        params:
          BOSH_INIT_ACCESS_KEY: {{bosh_init_access_key}}
          BOSH_INIT_SECRET_KEY: {{bosh_init_secret_key}}
          BOSH_SSH_TUNNEL_KEY: {{bosh_ssh_tunnel_key}}
          BOSH_TARGET_IP: 10.0.2.14
          BOSH_RESERVED_RANGES: [10.0.2.0-10.0.2.89, 10.0.2.100-10.0.2.255]
          BOSH_REDIS: true
      - do:
        - task: export-release
          file: bosh-src/ci/pipelines/compiled-releases/tasks/export-release.yml
          input_mapping:
            stemcell: ubuntu-trusty-3233-stemcell
            release: uaa-release-3232
          params:
            BOSH_TARGET_IP: 10.0.2.14
        - put: uaa-on-ubuntu-trusty-3233
          params:
            file: "compiled-release/*.tgz"
        ensure:
          task: teardown-director
          file: bosh-src/ci/pipelines/compiled-releases/tasks/teardown-director.yml
